<a href="https://colab.research.google.com/github/hut22929/pytorch-deep-learning/blob/master/DL_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
2+2

4

In [ ]:
!pip list

In [2]:
import torch
import numpy as np

In [ ]:
tensor2d = torch.randn(3,4)
tensor2d


tensor([[ 2.0690, -0.2719, -0.8715,  1.0630],
        [ 1.6949, -0.5582,  0.1093,  0.0229],
        [-0.6036, -3.1671, -0.5988,  1.7621]])

In [ ]:
tensor3d = torch.randn(3,4,5)
tensor3d.dtype

torch.float32

Tensor Math Operation

In [3]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])

In [5]:
#plus
tensor_a + tensor_b
torch.add(tensor_a, tensor_b)

tensor([ 6,  8, 10, 12])

In [7]:
#subtraction
tensor_b - tensor_a
torch.sub(tensor_b, tensor_a)

tensor([4, 4, 4, 4])

In [16]:
# Multiplication

a = tensor_a * tensor_b
b = torch.mul(tensor_a, tensor_b)
print(a,'\n' ,b)

tensor([ 5, 12, 21, 32]) 
 tensor([ 5, 12, 21, 32])


In [17]:
# Division
tensor_b / tensor_a
torch.div(tensor_b, tensor_a)

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [19]:
# Remainder Modulus
tensor_b % tensor_a
torch.remainder(tensor_b, tensor_a)

tensor([0, 0, 1, 0])

In [20]:
# Exponent , power
tensor_a ** tensor_b
torch.pow(tensor_a, tensor_b)


tensor([    1,    64,  2187, 65536])

In [21]:
#Reassigntment
tensor_a += tensor_b
tensor_a

tensor([ 6,  8, 10, 12])

In [24]:
tensor_a **= tensor_b
tensor_a

tensor([ -1024,   4096, -16384,  65536])